[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "day_1"

[[bin]]
name = "day_2"

[[bin]]
name = "day_3"

[[bin]]
name = "day_4"

[[bin]]
name = "day_5"

[[bin]]
name = "day_6"

[[bin]]
name = "day_7"
